###
GET http://localhost:8000/

###
POST http://localhost:8000/user/register
Content-Type: application/json

{
"email" : "admin@gmail.com",
"password" : "Admin123",
"firstName" : "LV",
"lastName" : "NT"
}
###
POST http://localhost:8000/user/login
Content-Type: application/json

{
"email" : "admin@gmail.com",
"password" : "admin@gmail.com"
}